// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5010/' | (string & {});
};

export type AccountModel = {
    login: string;
    avatarUrl: string;
    htmlUrl: string;
    type?: null | AccountType;
    repositories?: Array<SettingsRepositoryModel>;
};

export type AccountType = number;

export type AdvancedSecurity = {
    status?: null | string;
};

export type ApprovalResult = {
    repositoryOwner: string;
    repositoryName: string;
    pullRequestNumber: number | string;
    approved: boolean;
    merged: boolean;
    error?: null | string;
};

export type ApprovePullRequestsRequest = {
    pullRequests?: Array<PullRequestReference>;
};

export type BranchFilterRequest = {
    branchFilters?: Array<string>;
};

export type CheckStatus = 'Pending' | 'Success' | 'Failure' | 'Unknown';

export type DependabotSecurityUpdates = {
    status?: null | string;
};

export type LicenseMetadata = {
    key?: null | string;
    nodeId?: null | string;
    name?: null | string;
    spdxId?: null | string;
    url?: null | string;
    featured?: boolean;
};

export type Plan = {
    collaborators?: number | string;
    name?: null | string;
    privateRepos?: number | string;
    space?: number | string;
    billingEmail?: null | string;
    filledSeats?: number | string;
    seats?: number | string;
};

export type PullRequestModel = {
    id: number | string;
    number: number | string;
    nodeId: string;
    title: string;
    author: string;
    repositoryOwner: string;
    repositoryName: string;
    htmlUrl: string;
    headSha: string;
    headRef: string;
    createdAt: string;
    updatedAt: string;
    checkStatus: CheckStatus;
    mergeable?: null | boolean;
};

export type PullRequestReference = {
    owner: string;
    repo: string;
    number: number | string;
};

export type PullRequestsRequest = {
    repositories?: Array<RepositoryRequest>;
    authors?: Array<string>;
};

export type RagStatus = 'None' | 'Red' | 'Amber' | 'Green';

export type Repository = {
    url?: null | string;
    htmlUrl?: null | string;
    cloneUrl?: null | string;
    gitUrl?: null | string;
    sshUrl?: null | string;
    svnUrl?: null | string;
    mirrorUrl?: null | string;
    archiveUrl?: null | string;
    id?: number | string;
    nodeId?: null | string;
    owner?: User;
    name?: null | string;
    fullName?: null | string;
    isTemplate?: boolean;
    description?: null | string;
    homepage?: null | string;
    language?: null | string;
    private?: boolean;
    fork?: boolean;
    forksCount?: number | string;
    stargazersCount?: number | string;
    watchersCount?: number | string;
    defaultBranch?: null | string;
    openIssuesCount?: number | string;
    pushedAt?: null | string;
    createdAt?: string;
    updatedAt?: string;
    permissions?: RepositoryPermissions;
    parent?: Repository;
    source?: Repository;
    license?: LicenseMetadata;
    hasDiscussions?: boolean;
    hasIssues?: boolean;
    hasWiki?: boolean;
    hasDownloads?: boolean;
    allowRebaseMerge?: null | boolean;
    allowSquashMerge?: null | boolean;
    allowMergeCommit?: null | boolean;
    hasPages?: boolean;
    subscribersCount?: number | string;
    size?: number | string;
    archived?: boolean;
    topics?: null | Array<string>;
    deleteBranchOnMerge?: null | boolean;
    visibility?: null | RepositoryVisibility;
    allowAutoMerge?: null | boolean;
    allowUpdateBranch?: null | boolean;
    webCommitSignoffRequired?: null | boolean;
    securityAndAnalysis?: SecurityAndAnalysis;
};

export type RepositoryModel = {
    overallStatus?: RagStatus;
    workflows?: Array<WorkflowModel>;
    name: string;
    owner: string;
    nodeId: string;
    htmlUrl: string;
};

export type RepositoryPermissions = {
    admin?: boolean;
    maintain?: boolean;
    push?: boolean;
    triage?: boolean;
    pull?: boolean;
};

export type RepositoryRequest = {
    owner: string;
    name: string;
};

export type RepositoryVisibility = number;

export type RepositoryWorkflowRequest = {
    owner: string;
    name: string;
    workflows?: Array<number | string>;
};

export type SecretScanning = {
    status?: null | string;
};

export type SecretScanningPushProtection = {
    status?: null | string;
};

export type SecretScanningValidityChecks = {
    status?: null | string;
};

export type SecurityAndAnalysis = {
    advancedSecurity?: AdvancedSecurity;
    dependabotSecurityUpdates?: DependabotSecurityUpdates;
    secretScanning?: SecretScanning;
    secretScanningPushProtection?: SecretScanningPushProtection;
    secretScanningValidityChecks?: SecretScanningValidityChecks;
};

export type SettingsRepositoryModel = {
    fullName: string;
    workflows?: Array<WorkflowBase>;
    name: string;
    owner: string;
    nodeId: string;
    htmlUrl: string;
};

export type StringEnumOfWorkflowRunConclusion = string;

export type StringEnumOfWorkflowRunStatus = string;

export type User = {
    permissions?: RepositoryPermissions;
    siteAdmin?: boolean;
    suspendedAt?: null | string;
    suspended?: boolean;
    ldapDistinguishedName?: null | string;
    updatedAt?: string;
    avatarUrl?: null | string;
    bio?: null | string;
    blog?: null | string;
    collaborators?: null | number | string;
    company?: null | string;
    createdAt?: string;
    diskUsage?: null | number | string;
    email?: null | string;
    followers?: number | string;
    following?: number | string;
    hireable?: null | boolean;
    htmlUrl?: null | string;
    id?: number | string;
    nodeId?: null | string;
    location?: null | string;
    login?: null | string;
    name?: null | string;
    type?: null | AccountType;
    ownedPrivateRepos?: number | string;
    plan?: Plan;
    privateGists?: null | number | string;
    publicGists?: number | string;
    publicRepos?: number | string;
    totalPrivateRepos?: number | string;
    url?: null | string;
};

export type WorkflowBase = {
    id?: number | string;
    nodeId: string;
    name: string;
    htmlUrl: string;
};

export type WorkflowModel = {
    runs?: Array<WorkflowRunModel>;
    runStatus?: RagStatus;
    overallStatus?: RagStatus;
    id?: number | string;
    nodeId: string;
    name: string;
    htmlUrl: string;
};

export type WorkflowRunModel = {
    id: number | string;
    workflowId: number | string;
    nodeId: string;
    conclusion: null | StringEnumOfWorkflowRunConclusion;
    headBranch: string;
    event: string;
    runNumber: number | string;
    triggeringActor?: null | string;
    status: StringEnumOfWorkflowRunStatus;
    createdAt: string;
    updatedAt: string;
    htmlUrl: string;
    ragStatus?: RagStatus;
};

export type WorkflowRunsRequest = {
    branchFilters?: Array<string>;
};

export type WorkflowsRequest = {
    repositories?: Array<RepositoryWorkflowRequest>;
};

export type GetAdminSessionDebugData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/session/debug';
};

export type GetAdminSessionDebugResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories';
};

export type GetRepositoriesResponses = {
    /**
     * OK
     */
    200: Array<Repository>;
};

export type GetRepositoriesResponse = GetRepositoriesResponses[keyof GetRepositoriesResponses];

export type GetRepositoriesGroupedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/repositories/grouped';
};

export type GetRepositoriesGroupedResponses = {
    /**
     * OK
     */
    200: Array<AccountModel>;
};

export type GetRepositoriesGroupedResponse = GetRepositoriesGroupedResponses[keyof GetRepositoriesGroupedResponses];

export type PostWorkflowsData = {
    body: WorkflowsRequest;
    path?: never;
    query?: never;
    url: '/workflows';
};

export type PostWorkflowsResponses = {
    /**
     * OK
     */
    200: Array<RepositoryModel>;
};

export type PostWorkflowsResponse = PostWorkflowsResponses[keyof PostWorkflowsResponses];

export type GetWorkflowsForARepositoryData = {
    body: BranchFilterRequest;
    path: {
        owner: string;
        repo: string;
    };
    query?: never;
    url: '/repositories/{owner}/{repo}/workflows';
};

export type GetWorkflowsForARepositoryResponses = {
    /**
     * OK
     */
    200: Array<WorkflowModel>;
};

export type GetWorkflowsForARepositoryResponse = GetWorkflowsForARepositoryResponses[keyof GetWorkflowsForARepositoryResponses];

export type PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsData = {
    body: WorkflowRunsRequest;
    path: {
        owner: string;
        repo: string;
        workflowId: number | string;
    };
    query?: never;
    url: '/repositories/{owner}/{repo}/workflows/{workflowId}/runs';
};

export type PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponses = {
    /**
     * OK
     */
    200: Array<WorkflowRunModel>;
};

export type PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponse = PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponses[keyof PostRepositoriesByOwnerByRepoWorkflowsByWorkflowIdRunsResponses];

export type PostPullRequestsData = {
    body: PullRequestsRequest;
    path?: never;
    query?: never;
    url: '/pull-requests';
};

export type PostPullRequestsResponses = {
    /**
     * OK
     */
    200: Array<PullRequestModel>;
};

export type PostPullRequestsResponse = PostPullRequestsResponses[keyof PostPullRequestsResponses];

export type PostPullRequestsApproveData = {
    body: ApprovePullRequestsRequest;
    path?: never;
    query?: never;
    url: '/pull-requests/approve';
};

export type PostPullRequestsApproveResponses = {
    /**
     * OK
     */
    200: Array<ApprovalResult>;
};

export type PostPullRequestsApproveResponse = PostPullRequestsApproveResponses[keyof PostPullRequestsApproveResponses];
