/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PullRequestsIndexRouteImport } from './routes/pull-requests/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardListRouteImport } from './routes/dashboard/list'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsIndexRoute = PullRequestsIndexRouteImport.update({
  id: '/pull-requests/',
  path: '/pull-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListRoute = DashboardListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/list': typeof DashboardListRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pull-requests/': typeof PullRequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/list': typeof DashboardListRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/pull-requests': typeof PullRequestsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/list': typeof DashboardListRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/pull-requests/': typeof PullRequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/dashboard'
  | '/dashboard/list'
  | '/dashboard/overview'
  | '/dashboard/'
  | '/pull-requests/'
  | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/dashboard/list'
  | '/dashboard/overview'
  | '/dashboard'
  | '/pull-requests'
  | '/settings'
  id:
  | '__root__'
  | '/'
  | '/dashboard'
  | '/dashboard/list'
  | '/dashboard/overview'
  | '/dashboard/'
  | '/pull-requests/'
  | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PullRequestsIndexRoute: typeof PullRequestsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests/': {
      id: '/pull-requests/'
      path: '/pull-requests'
      fullPath: '/pull-requests/'
      preLoaderRoute: typeof PullRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/list': {
      id: '/dashboard/list'
      path: '/list'
      fullPath: '/dashboard/list'
      preLoaderRoute: typeof DashboardListRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardListRoute: typeof DashboardListRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardListRoute: DashboardListRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PullRequestsIndexRoute: PullRequestsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
